=== sbecker11/resume-parser-node/inputs/resume-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://not-a-real-domain/resume.schema.json",
  "title": "Resume tool",
  "description": "Defines structure of a resume json file",
  "type": "object",
  "properties": {
    "contactInformation": {
      "type": "string"
    },
    "positionOrProfessionalTitle": {
      "type": "string"
    },
    "professionalSummary": {
      "type": "string"
    },
    "workExperience": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "companyName": {
            "type": "string"
          },
          "location": {
            "type": "string"
          },
          "duration": {
            "type": "object",
            "properties": {
              "start": {
                "type": "string"
              },
              "end": {
                "type": "string"
              }
            },
            "required": [
              "end",
              "start"
            ]
          },
          "positionOrTitle": {
            "type": "string"
          },
          "responsibilities": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "skills": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "A list of skills relevant to the work experience"
          }
        },
        "required": [
          "companyName",
          "duration",
          "location",
          "positionOrTitle",
          "responsibilities"
        ]
      }
    },
    "education": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "institution": {
            "type": "string"
          },
          "degree": {
            "type": "string"
          }
        },
        "required": [
          "degree",
          "institution"
        ]
      }
    },
    "skills": {
      "type": "string"
    },
    "publications": {
      "type": "string"
    },
    "patents": {
      "type": "string"
    },
    "websites": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "certifications": {
      "type": "string"
    }
  },
  "required": [
    "certifications",
    "contactInformation",
    "education",
    "patents",
    "positionOrProfessionalTitle",
    "professionalSummary",
    "publications",
    "skills",
    "websites",
    "workExperience"
  ],
  "additionalProperties": false
}

=== sbecker11/resume-parser-node/outputs/data-engineer.json
{
  "contactInformation": "SHAWN BECKER",
  "positionOrProfessionalTitle": "DATA ENGINEERING / DATA ARCHITECTURE / MACHINE LEARNING",
  "professionalSummary": "As an experienced data engineering professional with expertise in Data Architecture and Machine Learning, I excel in problem-solving and leading teams to deliver innovative solutions to complex challenges across diverse industries, including entertainment, healthcare, finance, and manufacturing. My expertise includes creating scalable, secure, high-volume data pipelines leveraging cloud infrastructure and domain-specific data architecture while employing machine learning models to optimize data-driven decision-making processes. I thrive in dynamic environments, applying Agile methodologies to facilitate my team's focus on building working increments of well-architected solutions that meet product owners' expectations. Driven by a passion for continuous learning, I relish tackling new challenges and achieving excellence in every project.",
  "workExperience": [
    {
      "companyName": "Fannie Mae",
      "location": "Remote",
      "duration": {
        "start": "Mar 2024",
        "end": "Jun 2024"
      },
      "positionOrTitle": "Senior Data Engineer",
      "responsibilities": [
        "Documented processes to build, test, and deploy data pipeline components for in-house ETL framework.",
        "Extensive work with SQL, AWS Redshift, Glue, S3, IAM, Lambda, REST, Postman, SNS, and dbt.",
        "Utilized Agile practices with Jira, including backlog refinements, sprint planning, daily scrums, bi-weekly sprint reviews, and end-of-sprint retrospectives. Enabled the product owner to review each shipped product increment, allowing for potential revision or re-prioritization of backlog items."
      ],
      "skills": [
        "Apache Airflow",
        "Application Migrations",
        "Application Monitoring",
        "AWS CloudWatch",
        "AWS IAM",
        "AWS Lambda",
        "AWS Redshift",
        "AWS S3 Standard",
        "CI/CD",
        "Daily Scrum",
        "Data Catalog",
        "Data Engineering",
        "Databases",
        "Date Partitioning",
        "DevOps",
        "Docker",
        "Docker Compose",
        "ETL",
        "Git",
        "GitHub",
        "Jenkins",
        "Jira",
        "KPI",
        "Linux",
        "Microsoft Excel",
        "Python",
        "Scrum",
        "SDLC",
        "Sprint Planning",
        "Sprint Retrospective",
        "Sprint Review",
        "Sprints",
        "SQL",
        "Unit Testing"
      ]
    },
    {
      "companyName": "The Cigna Group",
      "location": "Remote",
      "duration": {
        "start": "Jun 2023",
        "end": "Dec 2023"
      },
      "positionOrTitle": "Senior Data Engineer",
      "responsibilities": [
        "Modernized apps via Jenkins CI/CD pipeline upgrade, integrating SetupTools, Artifactory/PyPI, SonarQube, and Xray.",
        "Investigated and implemented preparation of legacy ETL data pipeline components. Migration from on-prem Unity IoC apps to the AWS cloud using CDC.",
        "Ensured privacy and encryption standards for user data.",
        "Engineered Python REST API integration enabling credential retrieval from CyberArk's identity management platform using mutual TLS/SSL authentication via AWS API Gateway"
      ],
      "skills": [
        "Apache Airflow",
        "Application Migrations",
        "Application Monitoring",
        "AWS CloudWatch",
        "AWS Glue",
        "AWS IAM",
        "AWS KMS",
        "AWS Lambda",
        "AWS Redshift",
        "AWS S3 Standard",
        "AWS Secrets Manager",
        "AWS Step Functions",
        "Bash",
        "CI/CD",
        "Cyber Security",
        "Daily Scrum",
        "Data Engineering",
        "Databases",
        "DevOps",
        "Docker",
        "Docker Compose",
        "ETL",
        "Git",
        "GitHub",
        "Jenkins",
        "Jira",
        "KPI",
        "Linux",
        "Microsoft Excel",
        "Python",
        "REST APIs",
        "Scrum",
        "SDLC",
        "Sprint Planning",
        "Sprint Retrospective",
        "Sprint Review",
        "Sprints",
        "SQL",
        "Unit Testing"
      ]
    },
    {
      "companyName": "Warner Brothers Interactive Entertainment",
      "location": "Remote",
      "duration": {
        "start": "Sep 2022",
        "end": "Apr 2023"
      },
      "positionOrTitle": "Senior Data Engineer",
      "responsibilities": [
        "Utilized PySpark for ETL processes and Python for third-party integrations and dev-ops collaborations with Jenkins, DataDog, and ZenDesk. I leveraged Google BigQuery and AWS services, including Lambda, Aurora PostgreSQL, SalesForce, Sno, and AWS Glue.",
        "Developed high-volume pipeline ingress and RESTful API integrations, enabling efficient game telemetry and user PII data transfer between WB-distributed games and leading marketing platforms using Segment CDP, Kafka, Redshift, Glue, and Airflow for orchestration.",
        "Conducted exploration and statistical analysis of marketing data, including principal component analysis, eigenvector decomposition, dimensionality reduction, vectorization, Bayesian clustering, and collaborative filtering. I used Jupyter, Python, Pandas, NumPy, Sci-kit Learn, and Keras for analytical processing and Seaborn, Plotly, and Matplotlib for data visualization.",
        "Practiced Agile SDLC in Jira with spring planning, daily scrums, and bi-weekly sprint reviews."
      ]
    },
    {
      "companyName": "Angel Studios",
      "location": "Provo, Utah",
      "duration": {
        "start": "Dec 2021",
        "end": "Aug 2022"
      },
      "positionOrTitle": "Senior Data Engineer",
      "responsibilities": [
        "Used AWS SageMaker, Python, and Machine Learning packages, Pytorch and Keras, to build and optimize a supervised CNN for classifying movie frames from episodes stored in S3.",
        "Earned certifications in Advanced Learning Algorithms, Advanced SQL for Data Scientists, and Supervised Machine Learning: Regression & Classification, boosting professional skills.",
        "Conducted data exploration with machine learning algorithms using Jupyter, Python, Pandas, NumPy, Sci-kit Learn, and Keras for processing, and Seaborn, Plotly, and Matplotlib for data visualization to enhance analytical capabilities significantly.",
        "Created RESTful APIs to exchange data with external e-commerce and advertising partners.",
        "Created Snowflake ingestion scripts to support Looker business intelligence reporting..",
        "Developed effective Business Intelligence strategies using Looker and Tableau with Snowflake and Redshift for comprehensive sales and finance reporting."
      ],
      "skills": [
        "Ansible",
        "Applied Machine Learning",
        "AWS SageMaker",
        "Bash",
        "CI/CD",
        "CNN",
        "Daily Scrum",
        "Data Engineering",
        "Databases",
        "DevOps",
        "ETL",
        "Git",
        "GitHub",
        "Jenkins",
        "Jira",
        "Jupyter",
        "Keras",
        "KPI",
        "Linux",
        "Machine Learning",
        "MatPlotLib",
        "Microsoft Excel",
        "numpy",
        "Pandas",
        "Python",
        "PyTorch",
        "Regularization",
        "Scrum",
        "SDLC",
        "Statistical Data Analysis",
        "Supervised Classification",
        "Supervised Regression",
        "Tableau",
        "Unit Testing"
      ]
    },
    {
      "companyName": "Greenseed Data Laboratory",
      "location": "Orem, Utah",
      "duration": {
        "start": "Nov 2020",
        "end": "Nov 2021"
      },
      "positionOrTitle": "Senior Data Engineer",
      "responsibilities": [
        "Conducted advanced statistical exploration of real-estate sales data using Python, Pandas, NumPy, SciPy, and Scikit-learn.",
        "Implemented a CI/CD pipeline using GitHub Actions with Coverage, SonarQube, and Xray",
        "Designed and built a custom star-schema data warehouse on PostgreSQL, using dimensional modeling, featuring SCD type-2 tables sharing a common streaming facts table.",
        "Managed RESTful APIs used to exchange data with real-estate data teams and customers.",
        "Enhanced machine learning skills with tutorials for TensorFlow, PyTorch, and Keras using Kaggle datasets."
      ],
      "skills": [
        "AWS CloudFormation",
        "AWS CloudWatch",
        "AWS EC2",
        "AWS ECR",
        "AWS ECS",
        "AWS EFS",
        "AWS EKS",
        "AWS Fargate",
        "AWS IAM",
        "AWS Lambda",
        "AWS S3 Standard",
        "Bash",
        "CI/CD",
        "Daily Scrum",
        "Data Cleansing",
        "Data Engineering",
        "Databases",
        "DevOps",
        "Docker",
        "Docker Compose",
        "ETL",
        "Git",
        "GitHub",
        "Jenkins",
        "Jira",
        "KPI",
        "Kubernetes",
        "Linux",
        "Mentoring",
        "Microsoft Excel",
        "PostgreSQL",
        "Python",
        "REST APIs",
        "Scrum",
        "SDLC",
        "SQL",
        "Tech Project Manager",
        "Terraform",
        "Unit Testing"
      ]
    },
    {
      "companyName": "NuSkin",
      "location": "Provo, Utah",
      "duration": {
        "start": "Nov 2019",
        "end": "Nov 2020"
      },
      "positionOrTitle": "Senior Full Stack Developer",
      "responsibilities": [
        "Enhanced site registration and login pages by designing workflow and wireframes.",
        "Innovated Vue Vuetify components with NodeJS SCSS for improved functionality.",
        "Documented and launched new packages for company-wide use, enhancing efficiency.",
        "Internationalized content using Adobe Experience Cloud."
      ],
      "skills": [
        "Bash",
        "CI/CD",
        "Daily Scrum",
        "Data Engineering",
        "Databases",
        "DevOps",
